#!/usr/bin/env python
# coding: UTF-8

import sys
import no_ip_updater as noip


# Usuário e senha, e hosts padrões
# Se não forem definidos aqui, serão passados ao rodar o programa
username = None  # "username"
password = None  # "password"
hosts = None     # ["hostname.no-ip.org", "otherhost.servegame.com"]


# Detecta o ip atual
try:
	import no_ip_updater.getip as getip
	ip = getip.get_ip()
except:
	ip = None 



def run(args=sys.argv[1:]):
	import argparse
	import getpass
	
	parser = argparse.ArgumentParser(description="Atualiza hosts no-ip")
	add_arg = parser.add_argument
	add_arg("-u", "--username", action="store", dest="user",     type=str, help="No-IP username")
	add_arg("-p", "--password", action="store", dest="password", type=str, help="password to username")
	add_arg("-i", "--ip",       action="store", dest="ip",       type=str, help="IP to send")
	add_arg("-f", "--file",     action="store", dest="file",    nargs="+", help="not inplemented")
	add_arg("-host",            action="store", dest="host",    nargs="+", help="host to update")
	
	args = parser.parse_args()
	
	global username
	global password
	global hosts
	global ip
	
	# Procura os parametros correspondentes para usuário e senha
	if args.user:
		if args.password:
			username = args.user
			password = args.password
		else:
			password = None
			password = getpass.getpass()
			while not password:
				password = getpass.getpass("")
			username = args.user
	# Caso não, procura os padrões
	elif not username:
		username = raw_input("Username: ")
		while not username:
			username = raw_input()
		password = getpass.getpass()
		while not password:
			password = getpass.getpass("")
	
	if not password:
		password = getpass.getpass("Password for \"{}\": ".format(username))
		while not password:
			password = getpass.getpass("")
	
	# O mesmo para os hosts
	if args.host:
		hosts = args.host
	elif not hosts:
		hosts = raw_input("hosts: ").split()
		while not hosts:
			hosts = raw_input()
	
	# E para o ip
	if args.ip:
		ip = args.ip
	elif not ip:
		ip = raw_input("ip: ")
		while not ip:
			ip = raw_input()
	
	print
	print "=== No-IP Updater ==="
	
	noip.updateHosts(username, password, ip, hosts)

	print "====================="
	print
	
	
if __name__ == "__main__":
	run(sys.argv[1:])
#else:
	#print "This file is not to be imported"


