#!/usr/bin/env python3
# coding: UTF-8

import sys
import no_ip_updater as noip

def run():
	import argparse
	import getpass

	parser = argparse.ArgumentParser(description="Update No-IP hosts")
	add_arg = parser.add_argument
	add_arg("-u", "--username", action="store", dest="user",     type=str, help="No-IP account username" )
	add_arg("-p", "--password", action="store", dest="password", type=str, help="account password (NOT RECOMMENDED)" )
	add_arg("-i", "--ip",       action="store", dest="ip",       type=str, help="new host IP" )
	add_arg("-f", "--file",     action="store", dest="file",    nargs="+", help="NOT IMPLEMENTED" )
	add_arg("-host",            action="store", dest="host",    nargs="+", help="host(s) to update" )

	args = parser.parse_args()

	username = args.user
	password = args.password
	hosts = args.host
	ip = args.ip

	if not username:
		while not username:
			username = input("Username: ")

	if not password:
		while not password:
			password = getpass.getpass("Password: ")

	if not hosts:
		while not hosts:
			hostsStr = input("hosts: ")
			hosts = hostsStr.split()

	if not ip:
		# Detects the current IP
		try:
			print("Detecting current IP...")
			import no_ip_updater.getip as getip
			ip = getip.get_ip()
		except Exception as err:
			print("Can't detect current IP.")
			print(err)
			while not ip:
				ip = input("ip: ")

	print("ip: {}".format(ip))
	noip.updateHosts(username, password, ip, hosts)

if __name__ == "__main__":
	run()
